"""dashobard-primary-key

Revision ID: 47e3425d9e76
Revises: 7ad23910d65f
Create Date: 2024-08-13 08:10:37.483750

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47e3425d9e76"
down_revision: Union[str, None] = "7ad23910d65f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_dashboards_id", table_name="dashboards")
    op.drop_column("dashboards", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dashboards",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.create_index("ix_dashboards_id", "dashboards", ["id"], unique=False)
    # ### end Alembic commands ###
