"""dashboard

Revision ID: 7ad23910d65f
Revises: 228307ff4a5f
Create Date: 2024-08-08 08:41:33.084084

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ad23910d65f"
down_revision: Union[str, None] = "228307ff4a5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dashboards_id"), "dashboards", ["id"], unique=False)
    op.create_index(op.f("ix_dashboards_user_id"), "dashboards", ["user_id"], unique=False)
    op.create_index(op.f("ix_dashboards_uuid"), "dashboards", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dashboards_uuid"), table_name="dashboards")
    op.drop_index(op.f("ix_dashboards_user_id"), table_name="dashboards")
    op.drop_index(op.f("ix_dashboards_id"), table_name="dashboards")
    op.drop_table("dashboards")
    # ### end Alembic commands ###
