"""form_shared

Revision ID: 8bd5b66a1186
Revises: f9e57b4441c0
Create Date: 2024-09-16 08:00:55.226054

"""

from typing import Any, Sequence, Union

from alembic import op
from sqlalchemy import Boolean, Column, MetaData, Table, orm, update

# revision identifiers, used by Alembic.
revision: str = "8bd5b66a1186"
down_revision: Union[str, None] = "f9e57b4441c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("forms", Column("shared", Boolean(), nullable=True))
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = orm.Session(bind=bind)
    form_table: Any = Table("forms", MetaData(), autoload_with=bind)

    session.execute(update(form_table).values(shared=form_table.c.is_active))
    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("forms", "shared")
    # ### end Alembic commands ###
