"""form_records

Revision ID: 9b3eb2788072
Revises: e855f18a28fa
Create Date: 2024-09-17 08:00:08.444430

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9b3eb2788072"
down_revision: Union[str, None] = "e855f18a28fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_records",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("form_uuid", sa.Uuid(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_uuid"],
            ["forms.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_form_records_form_uuid"),
        "form_records",
        ["form_uuid"],
        unique=False,
    )
    op.create_index(op.f("ix_form_records_uuid"), "form_records", ["uuid"], unique=True)
    op.alter_column(
        "forms",
        "structure",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "forms",
        "structure",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_index(op.f("ix_form_records_uuid"), table_name="form_records")
    op.drop_index(op.f("ix_form_records_form_uuid"), table_name="form_records")
    op.drop_table("form_records")
    # ### end Alembic commands ###
