"""forms

Revision ID: a50edf75721d
Revises: 47e3425d9e76
Create Date: 2024-08-13 08:11:51.574196

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a50edf75721d"
down_revision: Union[str, None] = "47e3425d9e76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forms",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("dashboard_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dashboard_uuid"],
            ["dashboards.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_forms_dashboard_uuid"),
        "forms",
        ["dashboard_uuid"],
        unique=False,
    )
    op.create_index(op.f("ix_forms_uuid"), "forms", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_forms_uuid"), table_name="forms")
    op.drop_index(op.f("ix_forms_dashboard_uuid"), table_name="forms")
    op.drop_table("forms")
    # ### end Alembic commands ###
