"""delete_is_active

Revision ID: e855f18a28fa
Revises: 8bd5b66a1186
Create Date: 2024-09-17 07:50:24.882730

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e855f18a28fa"
down_revision: Union[str, None] = "8bd5b66a1186"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("forms", "shared", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_column("forms", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "forms",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.alter_column("forms", "shared", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
